name: Bug report
description: Report a bug to help Embark improve
labels: ["bug", "en"]

body:
  - type: markdown
    attributes:
      value: |
        # Bug report
      
  - type: textarea
    id: descr
    attributes:
      label: Bug description
      description: "A clear and concise description of what went wrong"
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: "What should one do to reproduce this bug"
      placeholder: |
        1. Open '...'
        2. Click '....'
        3. Get an error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: "What was expected to happen"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional info
    validations:
      required: false

