import tkinter
from typing import Any, Callable

from .core_rendering import CTkCanvas as CTkCanvas
from .core_rendering import DrawEngine as DrawEngine
from .core_widget_classes import CTkBaseClass as CTkBaseClass
from .font import CTkFont as CTkFont
from .theme import ThemeManager as ThemeManager

class CTkRadioButton(CTkBaseClass):
    def __init__(self, master: Any, width: int = 100, height: int = 22, radiobutton_width: int = 22, radiobutton_height: int = 22, corner_radius: int | None = None, border_width_unchecked: int | None = None, border_width_checked: int | None = None, bg_color: str | tuple[str, str] = "transparent", fg_color: str | tuple[str, str] | None = None, hover_color: str | tuple[str, str] | None = None, border_color: str | tuple[str, str] | None = None, text_color: str | tuple[str, str] | None = None, text_color_disabled: str | tuple[str, str] | None = None, text: str = "CTkRadioButton", font: tuple | CTkFont | None = None, textvariable: tkinter.Variable | None = None, variable: tkinter.Variable | None = None, value: int | str = 0, state: str = ..., hover: bool = True, command: Callable | Any = None, **kwargs) -> None: ...
    def destroy(self) -> None: ...
    def configure(self, require_redraw: bool = False, **kwargs) -> None: ...
    def cget(self, attribute_name: str) -> any: ...
    def invoke(self, event: int = 0) -> None: ...
    def select(self, from_variable_callback: bool = False) -> None: ...
    def deselect(self, from_variable_callback: bool = False) -> None: ...
    def bind(self, sequence: str = None, command: Callable = None, add: str | bool = True): ...
    def unbind(self, sequence: str = None, funcid: str = None): ...
    def focus(self): ...
    def focus_set(self): ...
    def focus_force(self): ...
