from typing import Any, Callable

from _typeshed import Incomplete

from .core_rendering import CTkCanvas as CTkCanvas
from .core_rendering import DrawEngine as DrawEngine
from .core_widget_classes import CTkBaseClass as CTkBaseClass
from .theme import ThemeManager as ThemeManager

class CTkScrollbar(CTkBaseClass):
    def __init__(self, master: Any, width: int | str | None = None, height: int | str | None = None, corner_radius: int | None = None, border_spacing: int | None = None, minimum_pixel_length: int = 20, bg_color: str | tuple[str, str] = "transparent", fg_color: str | tuple[str, str] | None = None, button_color: str | tuple[str, str] | None = None, button_hover_color: str | tuple[str, str] | None = None, hover: bool = True, command: Callable | Any = None, orientation: str = "vertical", **kwargs) -> None: ...
    def configure(self, require_redraw: bool = False, **kwargs) -> None: ...
    def cget(self, attribute_name: str) -> any: ...
    def set(self, start_value: float, end_value: float): ...
    def get(self): ...
    def bind(self, sequence: Incomplete | None = None, command: Incomplete | None = None, add: bool = True) -> None: ...
    def unbind(self, sequence: Incomplete | None = None, funcid: Incomplete | None = None) -> None: ...
    def focus(self): ...
    def focus_set(self): ...
    def focus_force(self): ...
