import tkinter
from typing import Any, Callable

from .core_rendering import CTkCanvas as CTkCanvas
from .core_rendering import DrawEngine as DrawEngine
from .core_widget_classes import CTkBaseClass as CTkBaseClass
from .font import CTkFont as CTkFont
from .image import CTkImage as CTkImage
from .theme import ThemeManager as ThemeManager

class CTkButton(CTkBaseClass):
    def __init__(self, master: Any, width: int = 140, height: int = 28, corner_radius: int | None = None, border_width: int | None = None, border_spacing: int = 2, bg_color: str | tuple[str, str] = "transparent", fg_color: str | tuple[str, str] | None = None, hover_color: str | tuple[str, str] | None = None, border_color: str | tuple[str, str] | None = None, text_color: str | tuple[str, str] | None = None, text_color_disabled: str | tuple[str, str] | None = None, background_corner_colors: tuple[str | tuple[str, str]] | None = None, round_width_to_even_numbers: bool = True, round_height_to_even_numbers: bool = True, text: str = "CTkButton", font: tuple | CTkFont | None = None, textvariable: tkinter.Variable | None = None, image: CTkImage | ImageTk.PhotoImage | None = None, state: str = "normal", hover: bool = True, command: Callable[[], Any] | None = None, compound: str = "left", anchor: str = "center", **kwargs) -> None: ...
    def destroy(self) -> None: ...
    def configure(self, require_redraw: bool = False, **kwargs) -> None: ...
    def cget(self, attribute_name: str) -> any: ...
    def invoke(self): ...
    def bind(self, sequence: str = None, command: Callable = None, add: str | bool = True): ...
    def unbind(self, sequence: str = None, funcid: str = None): ...
    def focus(self): ...
    def focus_set(self): ...
    def focus_force(self): ...
