import tkinter
from typing import Any, Callable

from _typeshed import Incomplete

from .core_rendering import CTkCanvas as CTkCanvas
from .core_rendering import DrawEngine as DrawEngine
from .core_widget_classes import CTkBaseClass as CTkBaseClass
from .font import CTkFont as CTkFont
from .theme import ThemeManager as ThemeManager

class CTkSwitch(CTkBaseClass):
    def __init__(self, master: Any, width: int = 100, height: int = 24, switch_width: int = 36, switch_height: int = 18, corner_radius: int | None = None, border_width: int | None = None, button_length: int | None = None, bg_color: str | tuple[str, str] = "transparent", fg_color: str | tuple[str, str] | None = None, border_color: str | tuple[str, str] = "transparent", progress_color: str | tuple[str, str] | None = None, button_color: str | tuple[str, str] | None = None, button_hover_color: str | tuple[str, str] | None = None, text_color: str | tuple[str, str] | None = None, text_color_disabled: str | tuple[str, str] | None = None, text: str = "CTkSwitch", font: tuple | CTkFont | None = None, textvariable: tkinter.Variable | None = None, onvalue: int | str = 1, offvalue: int | str = 0, variable: tkinter.Variable | None = None, hover: bool = True, command: Callable | Any = None, state: str = ..., **kwargs) -> None: ...
    def destroy(self) -> None: ...
    def configure(self, require_redraw: bool = False, **kwargs) -> None: ...
    def cget(self, attribute_name: str) -> any: ...
    def toggle(self, event: Incomplete | None = None) -> None: ...
    def select(self, from_variable_callback: bool = False) -> None: ...
    def deselect(self, from_variable_callback: bool = False) -> None: ...
    def get(self) -> int | str: ...
    def bind(self, sequence: str = None, command: Callable = None, add: str | bool = True): ...
    def unbind(self, sequence: str = None, funcid: str = None): ...
    def focus(self): ...
    def focus_set(self): ...
    def focus_force(self): ...
